# Generated by Django 2.1.5 on 2021-09-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20210906_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='mobile',
            field=models.CharField(max_length=200),
        ),
    ]
