# Generated by Django 2.1.5 on 2021-09-07 11:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20210906_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='passenger_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
