# Generated by Django 2.1.5 on 2021-09-07 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_passenger_passenger_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='passenger_code',
        ),
    ]
