# Generated by Django 2.1.5 on 2021-09-06 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=200)),
                ('age', models.IntegerField(max_length=3)),
                ('dob', models.DateTimeField(verbose_name='Date of Birth')),
                ('email', models.CharField(max_length=200)),
                ('mobile', models.IntegerField(max_length=12)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Gender')),
            ],
        ),
    ]
