# Generated by Django 2.1.5 on 2021-09-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
